PRAGMA foreign_keys = ON;

CREATE TABLE posts(
  postid INTEGER PRIMARY KEY AUTOINCREMENT,
  filename VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  price VARCHAR(64) NOT NULL,
  description VARCHAR(1024) NOT NULL,
  status VARCHAR(64) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags (
  tagid INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE post_tags (
  postid INTEGER NOT NULL,
  tagid INTEGER NOT NULL,
  PRIMARY KEY (postid, tagid),
  FOREIGN KEY (postid) REFERENCES posts(postid) ON DELETE CASCADE,
  FOREIGN KEY (tagid) REFERENCES tags(tagid) ON DELETE CASCADE
);
